### ISSUE TITLE
assembly a high heterozygous plant genome

### ISSUE THREAD

**Issue by yilunhuangyue** [ruanjue/wtdbg2#127]
Hi ruanjue,
I am assembly a high heterozygous plant genome with the haploid genome size of about 350M. I am assembled the genome by SMARTdenovo with default parameters, the assembled contigs was about 500Mb and N50 was 700K. Then I tried wtdbg2 with -AS 3 -R, the size of assembled contigs  were more reasonable (390M) but the contig N50 was only 400K.  Is there any parameters that could be  adjusted to improved the result by wtdbg2 or SMARTdenovo?

Thanks a lot for your help.

**Comment by ruanjue** [comment]
Have a try with `-p 17`. Otherwise please try use canu to correct raw reads and then send the corrected reads to SMARTdenovo or `wtdbg2 -x ccs`.

**Comment by yilunhuangyue** [comment]
Thanks for your quick response. I forgot mentioned that I have tried using canu corrected read and did not got improved assembled result. I will try -p 17.

**Comment by wangzhongkai1** [comment]
Hi dear jue ,
could you please explain the reason why you recommend the parameter -p 17 ? According to my experience and you recommendation issued before , the parameter -p 19 -k 1 would  lead to the best assembly results  and accordingly, it would spend the most time. 
AND dear yilunhuangyue,
could you please tell me if you have tested a better result ? Because I am also assemblying a genome of high heterozygous which counted to be about 2.2% by kmerfreq .And the result is so bad that I have to seek help from you .
Importantly , dear Jue,
I have issued before, but it did not work out for my genome. I will send you a detailed list of my problem in CHINESE to you personal e-mail , thank you a lot for your help!

**Comment by yilunhuangyue** [comment]
Hi ruanjue and wangzhongkai1,
I did not get better result as the recommend parameter. By the way, my genome shows a similar heterozygous ratio as yours@wangzhongkai1. 
I also tried SMARTdenovo using raw data and got good N50 values but with a larger genome size than expected. So i decide to reduced the rebundant sequences from contigs.
I hope for your message if you make any progress~

**Comment by wangzhongkai1** [comment]
thanks for your reply，I will tell you my results the mement i get it and hope you a good progress！


| |
Wangzk
Best wishes！
|
|
邮箱：15834186753@163.com
|

Signature is customized by Netease Mail Master

On 07/05/2019 23:26, yilunhuangyue wrote:

Hi ruanjue and wangzhongkai1,
I did not get better result as the recommend parameter. By the way, my genome shows a similar heterozygous ratio as yours@wangzhongkai1.
I also tried SMARTdenovo using raw data and got good N50 values but with a larger genome size than expected. So i decide to reduced the rebundant sequences from contigs.
I hope for your message if you make any progress~

**Comment by ruanjue** [comment]
Hi all, thanks for sharing the experiences. Please try more on your dataset.

**Comment by wangzhongkai1** [comment]
sorry to tell you that I didnot get a better result.

**Comment by ruanjue** [comment]
Try more assemblers, if still no good, just feel ok, not all genome can be assembled in a good contiguity based on current technology.
