### ISSUE TITLE
- A option: What do you mean by contained reads? 

### ISSUE THREAD

**Issue by GracelinTina** [ruanjue/wtdbg2#203]
I am using wtdbg2 for assembling a fish genome. When I change -S  3 -A 3 to -S 4 -A 4 (Rest of parameters used were p=23,k=0, L=10,000,e=3, s=0.05) the busco score changes dramatically (from 20% to 40%).  Also, when I use quickmerge to merge these two assemblies, N50 also changes dramatically. I am trying to understand how. Also -A means keep contained reads, what does it mean? Could you explain. Thanks.

**Comment by ruanjue** [comment]
Before BUSCO evaluation, you need to run polishment on the raw contigs. 

When you merge two assemblies, please keep in mind the brought mis-assemblies instead of N50 change.

`-A` means when it finds read i contains read j during the query of read i to all other reads, wtdbg2 will skip the turn of read j's query.
