### ISSUE TITLE
issue with visualising GFA using bandage

### ISSUE THREAD

**Issue by u2progress** [ruanjue/wtdbg2#208]
Hello, 

I want to view the assembly graph using bandage. I have converted the prefix.ctg.dot file to GFA using wtdbg-dot2gfa.pl, but  when I try to use the resulting file in bandage I get the following error: 'GFA file contains links with complex CIGAR strings (containing operators other than M). Bandage does not support edge overlaps that are not perfect, so the behaviour of such edges in this graph is not defined.'
What do you suggest?

**Comment by ruanjue** [comment]
Was it a problem of GFA different version? I haven't viewed the assembly graph.

**Comment by jflot** [comment]
It looks like the problem is that the GFA contains "0S" as a CIGAR string for contigs that do not overlap. Other assemblers that produce GFA (e.g., Flye) return "0M" in such case. If I replace "0S" with "0M" in the GFAs I obtain using wtdbg-dot2gfa.pl (using e.g sed -i 's/0S/0M/' *.gfa), I can open them in Bandage without problem ("S" in CIGAR normally stands for soft clip).

**Comment by unnatisonawala** [comment]
Thank you, will try that.
