### ISSUE TITLE
Error rate / haplotype collapsing

### ISSUE THREAD

**Issue by gbdias** [ruanjue/wtdbg2#40]
Hi Jue,

- wtdbg2 produces very interesting results. I am particularly impressed with the low level of duplication (haplotigs) in the final assemblies.
- Is there a combination of parameters that could reduce haplotype and repeat collapsing to produce an assembly with both alleles when you have heterozygous regions or structural variants? I am trying to replicate what Canu does, which is separating haplotypes that are 1-2% divergent.

Best,
Guilherme

**Comment by ruanjue** [comment]
Thanks Guilherme,

When wtdbg2 assembles raw long noisy reads, it is not sensitive with the sequence similarity, so that haplotigs will be collapsed into unique ones.

Recently, I add a option '-s <kmer_similarity>' to filter alignments of accurate long reads from CANU-correction or PacBio CCS. Please note that 1-2% sequence divergence is not the same value in kmer-divergence, maybe 10% or others, need to calculations or tests.

Best,
Jue

**Comment by gbdias** [comment]
Got it.
Thanks for the info Jue.

Best,
Guilherme
